appname: "validatetiny_example"

layout: "main"
charset: "UTF-8"

template: "template_toolkit"
engines:
  template_toolkit:
    encoding: "utf8"

plugins:
  ValidateTiny:
    rules_dir: validation
    error_prefix: err_
    is_full: 0
